steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:latest
      - .
      - --cache-from
      - us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - swift-api-demo
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:$SHORT_SHA
      - --port=8080
      - --region=us-central1
      - --memory=512Mi
      - --platform=managed
      - --allow-unauthenticated
      - --min-instances=0
      - --max-instances=5
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/swift/server:latest'
timeout: 1800s
